export const timelineElements = [
	{
		key: 1,
		time: "1 January",
		icon: "work",
		title: "Track Release",
		buttonText: "Read More",
		//   location: "",
		description:
			"Excited for innovation? Tracks launch Jan 1. Gear up to create and solve real-world challenges!",
	},
	{
		key: 2,
		time: "2 - 22 January",
		icon: "school",
		title: "Rolling Acceptance Idea Submission",
		buttonText: "Read More",
		//   location: "",
		description:
			"Limited seats! Submit ideas early at submit.ccstiet.com. Results within 36 hours. Don’t miss HackTU!",
	},
	{
		key: 3,
		time: "22 January",
		icon: "school",
		title: "Idea Submission Ends",
		buttonText: "Read More",
		//   location: "",
		description:
			"Idea submissions close Jan 22. Submit now at submit.ccstiet.com.",
	},
	{
		key: 4,
		time: "8 - 9 February",
		icon: "school",
		title: "Main HackTU 6.0 Day",
		buttonText: "Read More",
		//   location: "",
		description: "Offline round at Thapar Institute, Patiala. See you there!",
	},
	// {
	// 	key: 5,
	// 	time: "1AM",
	// 	icon: "school",
	// 	title: "Mini Game",
	// 	buttonText: "Read More",
	// 	//   location: "",
	// 	description: "Exciting Prizes to be Won!",
	// },
	// {
	// 	key: 6,
	// 	time: "11AM",
	// 	icon: "school",
	// 	title: "Hacking Time Elapsed",
	// 	buttonText: "Read More",
	// 	//   location: "",
	// 	description: "",
	// },
	// {
	// 	key: 7,
	// 	time: "12PM",
	// 	icon: "school",
	// 	title: "Selected Teams Announced",
	// 	buttonText: "Read More",
	// 	//   location: "",
	// 	description: "",
	// },
	// {
	// 	key: 9,
	// 	time: "12:30PM",
	// 	icon: "school",
	// 	title: "Pitching Round Starts",
	// 	buttonText: "Read More",
	// 	//   location: "",
	// 	description: "Prepare your Pitches!",
	// },
	// More elements can be added here
];
