const timelineElements = [
	{
		key: 1,
		time: "10AM",
		icon: "work",
		title: "Inaugration",
		buttonText: "Read More",
		//   location: "",
		description: "Opening speech and general instructions",
	},
	{
		key: 2,
		time: "11AM",
		icon: "school",
		title: "Hack Begins",
		buttonText: "Read More",
		//   location: "",
		description: "First brainstorm and idea. Then code and Innovate",
	},
	{
		key: 3,
		time: "3:30PM",
		icon: "school",
		title: "Mentor Session - Idea Validation",
		buttonText: "Read More",
		//   location: "",
		description: "Checkpoint 0",
	},
	{
		key: 4,
		time: "11PM",
		icon: "school",
		title: "Mentor Session - Idea Implementation",
		buttonText: "Read More",
		//   location: "",
		description: "Checkpoint 1",
	},
	{
		key: 5,
		time: "1AM",
		icon: "school",
		title: "Mini Game",
		buttonText: "Read More",
		//   location: "",
		description: "Exciting Prizes to be Won!",
	},
	{
		key: 6,
		time: "11AM",
		icon: "school",
		title: "Hacking Time Elapsed",
		buttonText: "Read More",
		//   location: "",
		description: "",
	},
	{
		key: 7,
		time: "12PM",
		icon: "school",
		title: "Selected Teams Announced",
		buttonText: "Read More",
		//   location: "",
		description: "",
	},
	{
		key: 8,
		time: "11AM",
		icon: "school",
		title: "Hacking Time Elapsed",
		buttonText: "Read More",
		//   location: "",
		description: "",
	},
	{
		key: 9,
		time: "12:30PM",
		icon: "school",
		title: "Pitching Round Starts",
		buttonText: "Read More",
		//   location: "",
		description: "Prepare your Pitches!",
	},
	// More elements can be added here
];

export default timelineElements;
